<a href="https://colab.research.google.com/github/gowriv05/BeautifulSoup/blob/main/BeautifulSoup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install requests bs4

Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->bs4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->bs4) (4.16.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2

In [ ]:
import requests

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
}

url = "https://en.wikipedia.org/wiki/List_of_highest-grossing_films"
html = requests.get(url, headers=headers).text
html

'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" lang="en" dir="ltr">\n<head>\n<meta charset="UTF-8">\n<title>List of highest-grossing films - Wikipedia</title>\n<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split(\'%2C\').forEach(function(pref){className=className.replace(new RegExp(\'(^| )\'+pref.replace(/-clientpref-\\w+$|[^\\w-]+/g,\'\')+\'-clientpref-\\\\w+( |$)\'),\'$1\'+pref+\'$2\');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"f3793d07-c642-4369-9ae0-e4d015a3086f","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_highest-grossing_films","wgTitle":"List of highest-grossing films","wgCurRevisionId":1376397352,"wgRevisionId":1376397352,"wgArticleId":59892,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Featured lists","Wikipedia extended-confirmed-protected pages","Use American English from December 2023","All Wikipedia articles written in American English","Use mdy dates from December 2023","CS1: unfit URL","Articles containing potentially dated statements from 2025","All articles containing potentially dated statements","CS1 uses Russian-language script (ru)","CS1 Russian-language sources (ru)","Webarchive template wayback links","CS1: long volume value","Wikipedia articles needing page number citations from November 2018","The Numbers ID not in Wikidata","Lists of highest-grossing films","Record progressions"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_highest-grossing_films","wgRelevantArticleId":59892,"wgTempUserName":null,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":["extendedconfirmed"],"wgRestrictionMove":["extendedconfirmed"],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":300000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Business":{"class":"FL","importance":"Mid"},"Film":{"class":"FL","importance":""},"Lists":{"class":"FL","importance":"Mid"},"Project-independent assessment":{"class":"FL","importance":""}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":["minimal-minerva-toolbar"],"assigned":{"minimal-minerva-toolbar":"control"},"subject_ids":{"minimal-minerva-toolbar":"awaiting"}},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q392108","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};\nRLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","mediawiki.skinning.content.parsoid":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","mediawiki.skins.legacy":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","mediawiki.page.media","ext.scribunto.logs","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","ext.wikimediaCustomizations.donorAccountCreation","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];</script>\n<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\\\","watchToken":"+\\\\","csrfToken":"+\\\\"});mw.user.options.set({"usecodemirror":1});\n}];});});</script>\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cmediawiki.skinning.content.parsoid%7Cmediawiki.skins.legacy%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022">\n<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>\n<meta name="ResourceLoaderDynamicStyles" content="">\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022">\n<meta name="generator" content="MediaWiki 1.47.0-wmf.20">\n<meta name="referrer" content="origin">\n<meta name="referrer" content="origin-when-cross-origin">\n<meta name="robots" content="max-image-preview:standard">\n<meta name="format-detection" content="telephone=no">\n<meta property="og:image" content="https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/Poster_-_Gone_With_the_Wind_01.jpg/960px-Poster_-_Gone_With_the_Wind_01.jpg?utm_source=en.wikipedia.org&amp;utm_campaign=index&amp;utm_content=thumbnail">\n<meta property="og:image:width" content="779">\n<meta property="og:image:height" content="1200">\n<meta name="viewport" content="width=1120">\n<meta property="og:title" content="List of highest-grossing films - Wikipedia">\n<meta property="og:type" content="website">\n<link rel="preconnect" href="//thumb.wikimedia.org">\n<link rel="apple-touch-icon" href="/static/apple-touch/wikipedia.png">\n<link rel="icon" href="/static/favicon/wikipedia.ico">\n<link rel="search" type="application/opensearchdescription+xml" href="/w/rest.php/v1/search" title="Wikipedia (en)">\n<link rel="EditURI" type="application/rsd+xml" href="//en.wikipedia.org/w/api.php?action=rsd">\n<link rel="canonical" href="https://en.wikipedia.org/wiki/List_of_highest-grossing_films">\n<link rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">\n<link rel="alternate" type="application/atom+xml" title="Wikipedia Atom feed" href="/w/index.php?title=Special:RecentChanges&amp;feed=atom">\n<link rel="dns-prefetch" href="//meta.wikimedia.org" />\n<link rel="dns-prefetch" href="auth.wikimedia.org">\n</head>\n<body class="test-kitchen-experiment-minimal-minerva-toolbar test-kitchen-experiment-minimal-minerva-toolbar-control skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-List_of_highest-grossing_films rootpage-List_of_highest-grossing_films skin-vector-2022 action-view">\n<div id="mw-aria-live-region" class="mw-aria-live-region" aria-live="polite"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>\n<div class="vector-header-container">\n\t<header class="vector-header mw-header no-font-mode-scale">\n\t\t<div class="vector-header-start">\n\t\t\t<nav class="vector-main-menu-landmark" aria-label="Site">\n\t\t\t\t\n<div id="vector-main-menu-dropdown" class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right"  title="Main menu" >\n\t<input type="checkbox" id="vector-main-menu-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-main-menu-dropdown" class="vector-dropdown-checkbox "  aria-label="Main menu"   >\n\t<label id="vector-main-menu-dropdown-label" for="vector-main-menu-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon"></span>\n\n<span class="vector-dropdown-label-text">Main menu</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\t\t<div id="vector-main-menu-unpinned-container" class="vector-unpinned-container">\n\t\t\n<div id="vector-main-menu" class="vector-main-menu vector-pinnable-element">\n\t<div\n\tclass="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned"\n\tdata-feature-name="main-menu-pinned"\n\tdata-pinnable-element-id="vector-main-menu"\n\tdata-pinned-container-id="vector-main-menu-pinned-container"\n\tdata-unpinned-container-id="vector-main-menu-unpinned-container"\n>\n\t<div class="vector-pinnable-header-label">Main menu</div>\n\t<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin" aria-label="Move Main menu to sidebar">move to sidebar</button>\n\t<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin" aria-label="Hide Main menu">hide</button>\n</div>\n\n\t\n<div id="p-navigation" class="vector-menu mw-portlet mw-portlet-navigation"  >\n\t<div class="vector-menu-heading">\n\t\tNavigation\n\t</div>\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="n-mainpage-description" class="mw-list-item"><a href="/wiki/Main_Page" title="Visit the main page [z]" accesskey="z"><span>Main page</span></a></li><li id="n-contents" class="mw-list-item"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li id="n-currentevents" class="mw-list-item"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li id="n-randompage" class="mw-list-item"><a href="/wiki/Special:Random" title="Visit a randomly selected article [x]" accesskey="x"><span>Random article</span></a></li><li id="n-aboutsite" class="mw-list-item"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li id="n-contactpage" class="mw-list-item"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-interaction" class="vector-menu mw-portlet mw-portlet-interaction"  >\n\t<div class="vector-menu-heading">\n\t\tContribute\n\t</div>\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="n-help" class="mw-list-item"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li id="n-introduction" class="mw-list-item"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li id="n-portal" class="mw-list-item"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li id="n-recentchanges" class="mw-list-item"><a href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]" accesskey="r"><span>Recent changes</span></a></li><li id="n-upload" class="mw-list-item"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li id="n-specialpages" class="mw-list-item"><a href="/wiki/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q"><span>Special pages</span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n</div>\n\n\t\t\t\t</div>\n\n\t</div>\n</div>\n\n\t\t</nav>\n\t\t\t\n<a href="/wiki/Main_Page" class="mw-logo">\n\t<img class="mw-logo-icon" src="/static/images/icons/enwiki-25.svg" alt="" aria-hidden="true" height="50" width="50">\n\t<span class="mw-logo-container skin-invert">\n\t\t<img class="mw-logo-wordmark" alt="Wikipedia" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;">\n\t\t<img class="mw-logo-tagline" alt="The Free Encyclopedia" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" width="140" height="11" style="width: 8.75em; height: 0.6875em;">\n\t</span>\n</a>\n\n\t\t</div>\n\t\t<div class="vector-header-end">\n\t\t\t\n<div id="p-search" role="search" class="vector-search-box-vue  vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box">\n\t<a href="/wiki/Special:Search" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" title="Search Wikipedia [f]" accesskey="f"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon"></span>\n\n<span>Search</span>\n\t</a>\n\t<div class="vector-typeahead-search-container">\n\t\t<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">\n\t\t\t<form action="/w/index.php" id="searchform" class="cdx-search-input cdx-search-input--has-end-button">\n\t\t\t\t<div id="simpleSearch" class="cdx-search-input__input-wrapper"  data-search-loc="header-moved">\n\t\t\t\t\t<div class="cdx-text-input cdx-text-input--has-start-icon">\n\t\t\t\t\t\t<input\n\t\t\t\t\t\t\tclass="cdx-text-input__input mw-searchInput" autocomplete="off"\n\t\t\t\t\t\t\t type="search" name="search" placeholder="Search Wikipedia" aria-label="Search Wikipedia" autocapitalize="none" spellcheck="false" title="Search Wikipedia [f]" accesskey="f" id="searchInput"\n\t\t\t\t\t\t\t>\n\t\t\t\t\t\t<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>\n\t\t\t\t\t</div>\n\t\t\t\t\t<input type="hidden" name="title" value="Special:Search">\n\t\t\t\t</div>\n\t\t\t\t<button class="cdx-button cdx-search-input__end-button">Search</button>\n\t\t\t</form>\n\t\t</div>\n\t</div>\n</div>\n\n\t\t\t<nav class="vector-user-links vector-user-links-wide" aria-label="Personal tools">\n\t<div class="vector-user-links-main">\n\t\n<div id="p-vector-user-menu-preferences" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-vector-user-menu-userpage" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t<nav class="vector-appearance-landmark" aria-label="Appearance">\n\t\t\n<div id="vector-appearance-dropdown" class="vector-dropdown "  title="Change the appearance of the page&#039;s font size, width, and color" >\n\t<input type="checkbox" id="vector-appearance-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-appearance-dropdown" class="vector-dropdown-checkbox "  aria-label="Appearance"   >\n\t<label id="vector-appearance-dropdown-label" for="vector-appearance-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon"></span>\n\n<span class="vector-dropdown-label-text">Appearance</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\t<div id="vector-appearance-unpinned-container" class="vector-unpinned-container">\n\t\t\t\t\n\t\t\t</div>\n\t\t\n\t</div>\n</div>\n\n\t</nav>\n\t\n<div id="p-vector-user-menu-notifications" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-vector-user-menu-overflow" class="vector-menu mw-portlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t<li id="pt-sitesupport-2" class="mw-list-item vector-menu-item--collapsible"><a data-mw-interface  href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en" data-mw-donate-attempt="top_link" class=""><span>Donate</span></a>\n</li>\n<li id="pt-createaccount-2" class="mw-list-item vector-menu-item--collapsible"><a data-mw-interface  href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+highest-grossing+films" title="You are encouraged to create an account and log in; however, it is not mandatory" class=""><span>Create account</span></a>\n</li>\n<li id="pt-login-2" class="mw-list-item vector-menu-item--collapsible"><a data-mw-interface  href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+highest-grossing+films" title="You&#039;re encouraged to log in; however, it&#039;s not mandatory. [o]" accesskey="o" class=""><span>Log in</span></a>\n</li>\n\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t</div>\n\t\n<div id="vector-user-links-dropdown" class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out vector-user-links-dropdown--collapsible"  title="Log in and more options" >\n\t<input type="checkbox" id="vector-user-links-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-user-links-dropdown" class="vector-dropdown-checkbox "  aria-label="Personal tools"   >\n\t<label id="vector-user-links-dropdown-label" for="vector-user-links-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup=BeautifulSoup(html,'html.parser')
soup

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of highest-grossing films - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"f3793d07-c642-4369-9ae0-e4d015a3086f","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_highest-grossing_films","wgTitle":"List of highest-grossing films","wgCurRevisionId":1376397352,"wgRevisionId":1376397352,"wgArticleId":59892,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Featured lists","Wikipedia extended-confirmed-protected pages","Use American English from December 2023","All Wikipedia articles written in American English","Use mdy dates from December 2023","CS1: unfit URL","Articles containing potentially dated statements from 2025","All articles containing potentially dated statements","CS1 uses Russian-language script (ru)","CS1 Russian-language sources (ru)","Webarchive template wayback links","CS1: long volume value","Wikipedia articles needing page number citations from November 2018","The Numbers ID not in Wikidata","Lists of highest-grossing films","Record progressions"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_highest-grossing_films","wgRelevantArticleId":59892,"wgTempUserName":null,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":["extendedconfirmed"],"wgRestrictionMove":["extendedconfirmed"],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":300000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Business":{"class":"FL","importance":"Mid"},"Film":{"class":"FL","importance":""},"Lists":{"class":"FL","importance":"Mid"},"Project-independent assessment":{"class":"FL","importance":""}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":["minimal-minerva-toolbar"],"assigned":{"minimal-minerva-toolbar":"control"},"subject_ids":{"minimal-minerva-toolbar":"awaiting"}},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q392108","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","mediawiki.skinning.content.parsoid":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","mediawiki.skins.legacy":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","mediawiki.page.media","ext.scribunto.logs","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","ext.wikimediaCustomizations.donorAccountCreation","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});mw.user.options.set({"usecodemirror":1});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cmediawiki.skinning.content.parsoid%7Cmediawiki.skins.legacy%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.47.0-wmf.20" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/Poster_-_Gone_With_the_Wind_01.jpg/960px-Poster_-_Gone_With_the_Wind_01.jpg?utm_source=en.wikipedia.org&amp;utm_campaign=index&amp;utm_content=thumbnail" property="og:image"/>
<meta content="779" property="og:image:width"/>
<meta content="1200" property="og:image:height"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of highest-grossing films - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//thumb.wikimedia.org" rel="preconnect"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_highest-grossing_films" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch">
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</link></head>
<body class="test-kitchen-experiment-minimal-minerva-toolbar test-kitchen-experiment-minimal-minerva-toolbar-control skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-List_of_highest-grossing_films rootpage-List_of_highest-grossing_films skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport-2"><a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+highest-grossing+films" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-login-2"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+highest-grossing+films" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out vector-user-links-dropdown--collapsible" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-userAvatar mw-ui-icon-wikimedia-userAvatar cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">

In [ ]:
print(soup.prettify)

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   List of highest-grossing films - Wikipedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"f3793d07-c642-4369-9ae0-e4d015a3086f","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_highest-grossing_films","wgTitle":"List of highest-grossing films","wgCurRevisionId":1376397352,"wgRevisionId":1376397352,"wgArticleId":59892,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Featured lists","Wikipedia extended-confirmed-protected pages","Use American English from December 2023","All Wikipedia articles written in American English","Use mdy dates from December 2023","CS1: unfit URL","Articles containing potentially dated statements from 2025","All articles containing potentially dated statements","CS1 uses Russian-language script (ru)","CS1 Russian-language sources (ru)","Webarchive template wayback links","CS1: long volume value","Wikipedia articles needing page number citations from November 2018","The Numbers ID not in Wikidata","Lists of highest-grossing films","Record progressions"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_highest-grossing_films","wgRelevantArticleId":59892,"wgTempUserName":null,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":["extendedconfirmed"],"wgRestrictionMove":["extendedconfirmed"],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":300000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Business":{"class":"FL","importance":"Mid"},"Film":{"class":"FL","importance":""},"Lists":{"class":"FL","importance":"Mid"},"Project-independent assessment":{"class":"FL","importance":""}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":["minimal-minerva-toolbar"],"assigned":{"minimal-minerva-toolbar":"control"},"subject_ids":{"minimal-minerva-toolbar":"awaiting"}},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q392108","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","mediawiki.skinning.content.parsoid":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","mediawiki.skins.legacy":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","mediawiki.page.media","ext.scribunto.logs","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","ext.wikimediaCustomizations.donorAccountCreation","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];
  </script>
  <script>
   (RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});mw.user.options.set({"usecodemirror":1});
}];});});
  </script>
  <link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cmediawiki.skinning.content.parsoid%7Cmediawiki.skins.legacy%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022">
  </script>
  <meta content="" name="ResourceLoaderDynamicStyles"/>
  <link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <meta content="MediaWiki 1.47.0-wmf.20" name="generator"/>
  <meta content="origin" name="referrer"/>
  <meta content="origin-when-cross-origin" name="referrer"/>
  <meta content="max-image-preview:standard" name="robots"/>
  <meta content="telephone=no" name="format-detection"/>
  <meta content="https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/Poster_-_Gone_With_the_Wind_01.jpg/960px-Poster_-_Gone_With_the_Wind_01.jpg?utm_source=en.wikipedia.org&amp;utm_campaign=index&amp;utm_content=thumbnail" property="og:image"/>
  <meta content="779" property="og:image:width"/>
  <meta content="1200" property="og:image:height"/>
  <meta content="width=1120" name="viewport"/>
  <meta content="List of highest-grossing films - Wikipedia" property="og:title"/>
  <meta content="website" property="og:type"/>
  <link href="//thumb.wikimedia.org" rel="preconnect"/>
  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
  <link href="/static/favicon/wikipedia.ico" rel="icon"/>
  <link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
  <link href="https://en.wikipedia.org/wiki/List_of_highest-grossing_films" rel="canonical"/>
  <link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
  <link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
  <link href="//meta.wikimedia.org" rel="dns-prefetch">
   <link href="auth.wikimedia.org" rel="dns-prefetch"/>
  </link>
 </head>
 <body class="test-kitchen-experiment-minimal-minerva-toolbar test-kitchen-experiment-minimal-minerva-toolbar-control skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-List_of_highest-grossing_films rootpage-List_of_highest-grossing_films skin-vector-2022 action-view">
  <div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region">
  </div>
  <a class="mw-jump-link" href="#bodyContent">
   Jump to content
  </a>
  <div class="vector-header-container">
   <header class="vector-header mw-header no-font-mode-scale">
    <div class="vector-header-start">
     <nav aria-label="Site" class="vector-main-menu-landmark">
      <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
       <input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
       <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">
        <span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon">
        </span>
        <span class="vector-dropdown-label-text">
         Main menu
        </span>
       </label>
       <div class="vector-dropdown-content">
        <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
         <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
          <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
           <div class="vector-pinnable-header-label">
            Main menu
           </div>
           <button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">
            move to sidebar
           </button>
           <button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">
            hide
           </button>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
           <div class="vector-menu-heading">
            Navigation
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-mainpage-description">
              <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]">
               <span>
                Main page
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contents">
              <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia">
               <span>
                Contents
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-currentevents">
              <a href="/wiki/Portal:Current_events" title="Articles related to current events">
               <span>
                Current events
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-randompage">
              <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]">
               <span>
                Random article
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-aboutsite">
              <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works">
               <span>
                About Wikipedia
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contactpage">
              <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia">
               <span>
                Contact us
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
           <div class="vector-menu-heading">
            Contribute
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-help">
              <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia">
               <span>
                Help
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-introduction">
              <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia">
               <span>
                Learn to edit
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-portal">
              <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors">
               <span>
                Community portal
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-recentchanges">
              <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]">
               <span>
                Recent changes
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-upload">
              <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia">
               <span>
                Upload file
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-specialpages">
              <a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]">
               <span>
                Special pages
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </nav>
     <a class="mw-logo" href="/wiki/Main_Page">
      <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
      <span class="mw-logo-container skin-invert">
       <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
       <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
      </span>
     </a>
    </div>
    <div class="vector-header-end">
     <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
      <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]">
       <span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon">
       </span>
       <span>
        Search
       </span>
      </a>
      <div class="vector-typeahead-search-container">
       <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
        <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
         <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
          <div class="cdx-text-input cdx-text-input--has-start-icon">
           <input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
           <span class="cdx-text-input__icon cdx-text-input__start-icon">
           </span>
          </div>
          <input name="title" type="hidden" value="Special:Search"/>
         </div>
         <button class="cdx-button cdx-search-input__end-button">
          Search
         </button>
        </form>
       </div>
      </div>
     </div>
     <nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
      <div class="vector-user-links-main">
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <nav aria-label="Appearance" class="vector-appearance-landmark">
        <div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
         <input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
         <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label">
          <span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon">
          </span>
          <span class="vector-dropdown-label-text">
           Appearance
          </span>
         </label>
         <div class="vector-dropdown-content">
          <div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
          </div>
         </div>
        </div>
       </nav>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">

In [ ]:
soup.find('table')

<table class="wikitable sortable plainrowheaders sticky-header col4right col5center col6center" id="mwxg">
<caption id="mwxw">Highest-grossing films<sup about="#mwt53" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-12"}}' id="cite_ref-12" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-12" id="mwyA"><span class="mw-reflink-text" id="mwyQ"><span class="cite-bracket" id="mwyg">[</span>12<span class="cite-bracket" id="mwyw">]</span></span></a></sup></caption>
<!--When using "data&#x2D;sort&#x2D;value" use the first release date, not the U.S. one.-->
<tbody id="mwzA"><tr id="mwzQ"><th id="mwzg">Rank</th>
<th id="mwzw">Peak</th>
<th class="unsortable" id="mw0A">Title</th>
<th class="unsortable" id="mw0Q">Worldwide gross</th>
<th id="mw0g">Year</th>
<th class="unsortable" id="mw0w"><abbr about="#mwt54" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mw1A\"&gt;References&lt;/span&gt;"}]],"parts":[{"template":{"target":{"wt":"abbr","href":"./Template:Abbr"},"params":{"1":{"wt":"Ref"},"2":{"wt":"References"}},"i":0}}]}' id="mw1Q" title="References" typeof="mw:Transclusion mw:ExpandedAttrs">Ref</abbr></th></tr>
<tr id="mw1g"><!-- This is an international chart and the film may still be on its theater run outside the U.S. even after its U.S. home video release. The highlighting alerts readers and editors to the fact that its gross is still being updated. Please do not remove the highlight too early -->
<td id="mw1w">1</td>
<td id="mw2A">1</td>
<th id="mw2Q" scope="row"><i id="mw2g"><a href="https://en.wikipedia.org/wiki/Avatar_(2009_film)" id="mw2w" rel="mw:WikiLink" title="Avatar (2009 film)">Avatar</a></i></th>
<td id="mw3A">$2,923,710,708</td>
<td id="mw3Q">2009</td>
<td id="mw3g"><sup about="#mwt56" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"#","name":"avatar"}}' id="cite_ref-avatar_13-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-avatar-13" id="mw3w"><span class="mw-reflink-text" id="mw4A"><span class="cite-bracket" id="mw4Q">[</span># 1<span class="cite-bracket" id="mw4g">]</span></span></a></sup><sup about="#mwt59" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"avatar peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-avatar_peak-14"}}' id="cite_ref-avatar_peak_14-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-avatar_peak-14" id="mw4w"><span class="mw-reflink-text" id="mw5A"><span class="cite-bracket" id="mw5Q">[</span># 2<span class="cite-bracket" id="mw5g">]</span></span></a></sup></td></tr>
<tr id="mw5w">
<td id="mw6A">2</td>
<td id="mw6Q">1</td>
<th id="mw6g" scope="row" style="background:#b6fcb6;"><i id="mw6w"><a href="https://en.wikipedia.org/wiki/Avengers:_Endgame" id="mw7A" rel="mw:WikiLink" title="Avengers: Endgame">Avengers: Endgame</a></i> †</th>
<td id="mw7Q">$<span about="#mwt60" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:2797501328+&lt;!--ENCORE--&gt;0}}","function":"formatnum"},"params":{},"i":0}}]}' id="mw7g" typeof="mw:Transclusion">2,797,501,328</span><!-- NOTE: DO NOT "fix" the gross for Endgame, PER [[WP:BOXOFFICE]]. --></td>
<td data-sort-value="2019-04" id="mw7w">2019</td>
<td id="mw8A"><sup about="#mwt64" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"endgame","group":"#"},"body":{"id":"mw-reference-text-cite_note-endgame-15"}}' id="cite_ref-endgame_15-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-endgame-15" id="mw8Q"><span class="mw-reflink-text" id="mw8g"><span class="cite-bracket" id="mw8w">[</span># 3<span class="cite-bracket" id="mw9A">]</span></span></a></sup><sup about="#mwt67" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"endgame peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-endgame_peak-16"}}' id="cite_ref-endgame_peak_16-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-endgame_peak-16" id="mw9Q"><span class="mw-reflink-text" id="mw9g"><span class="cite-bracket" id="mw9w">[</span># 4<span class="cite-bracket" id="mw-A">]</span></span></a></sup></td></tr>
<tr id="mw-Q">
<td id="mw-g">3</td>
<td id="mw-w">3</td>
<th id="mw_A" scope="row" style="background:#b6fcb6;"><i id="mw_Q"><a href="https://en.wikipedia.org/wiki/Spider-Man:_Brand_New_Day" id="mw_g" rel="mw:WikiLink" title="Spider-Man: Brand New Day">Spider-Man: Brand New Day</a></i> †</th>
<td id="mw_w">$2,479,827,325<!-- DO NOT USE The Numbers instead of Box Office Mojo, BOM takes priority in the main table unless it is demonstrably wrong --></td>
<td data-sort-value="2026-07" id="mwAQA">2026</td>
<td id="mwAQE"><sup about="#mwt70" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"bnd","group":"#"},"body":{"id":"mw-reference-text-cite_note-bnd-17"}}' id="cite_ref-bnd_17-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-bnd-17" id="mwAQI"><span class="mw-reflink-text" id="mwAQM"><span class="cite-bracket" id="mwAQQ">[</span># 5<span class="cite-bracket" id="mwAQU">]</span></span></a></sup></td></tr>
<tr id="mwAQY">
<td id="mwAQc">4</td>
<td id="mwAQg">3</td>
<th id="mwAQk" scope="row"><i id="mwAQo"><a href="https://en.wikipedia.org/wiki/Avatar:_The_Way_of_Water" id="mwAQs" rel="mw:WikiLink" title="Avatar: The Way of Water">Avatar: The Way of Water</a></i></th>
<td id="mwAQw">$2,334,484,620</td>
<td data-sort-value="2022-12" id="mwAQ0">2022</td>
<td id="mwAQ4"><sup about="#mwt71" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"avatar2","group":"#"}}' id="cite_ref-avatar2_18-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-avatar2-18" id="mwAQ8"><span class="mw-reflink-text" id="mwARA"><span class="cite-bracket" id="mwARE">[</span># 6<span class="cite-bracket" id="mwARI">]</span></span></a></sup><sup about="#mwt74" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"avatar 2 peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-avatar_2_peak-19"}}' id="cite_ref-avatar_2_peak_19-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-avatar_2_peak-19" id="mwARM"><span class="mw-reflink-text" id="mwARQ"><span class="cite-bracket" id="mwARU">[</span># 7<span class="cite-bracket" id="mwARY">]</span></span></a></sup></td></tr>
<tr id="mwARc">
<td id="mwARg">5</td>
<td id="mwARk">1</td>
<th id="mwARo" scope="row"><i id="mwARs"><a href="https://en.wikipedia.org/wiki/Titanic_(1997_film)" id="mwARw" rel="mw:WikiLink" title="Titanic (1997 film)">Titanic</a></i></th>
<td id="mwAR0"><sup about="#mwt75" class="plainlinks nourlexpansion citation" data-mw='{"parts":[{"template":{"target":{"wt":"ref","href":"./Template:Ref"},"params":{"1":{"wt":"Titanic"},"2":{"wt":"T"}},"i":0}}]}' id="ref_Titanic" typeof="mw:Transclusion"><a class="mw-selflink-fragment" href="#endnote_Titanic" rel="mw:WikiLink">T</a></sup>$<span about="#mwt76" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:1843373318+343550770+691642+71352+70219746}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwAR4" typeof="mw:Transclusion">2,257,906,828</span><!-- NOTE: DO NOT "fix" the gross for Titanic. BOM is double&#x2D;counting in the 2012 3D gross. See archived citation for correct amounts. --></td>
<td id="mwAR8">1997</td>
<td id="mwASA"><sup about="#mwt78" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"#","name":"titanic"}}' id="cite_ref-titanic_20-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-titanic-20" id="mwASE"><span class="mw-reflink-text" id="mwASI"><span class="cite-bracket" id="mwASM">[</span># 8<span class="cite-bracket" id="mwASQ">]</span></span></a></sup><sup about="#mwt81" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"titanic peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-titanic_peak-21"}}' id="cite_ref-titanic_peak_21-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-titanic_peak-21" id="mwASU"><span class="mw-reflink-text" id="mwASY"><span class="cite-bracket" id="mwASc">[</span># 9<span class="cite-bracket" id="mwASg">]</span></span></a></sup></td></tr>
<tr id="mwASk">
<td id="mwASo">6</td>
<td id="mwASs">5</td>
<th id="mwASw" scope="row"><i id="mwAS0"><a href="https://en.wikipedia.org/wiki/Ne_Zha_2" id="mwAS4" rel="mw:WikiLink" title="Ne Zha 2">Ne Zha 2</a></i></th>
<td id="mwAS8"><sup about="#mwt82" class="plainlinks nourlexpansion citation" data-mw='{"parts":[{"template":{"target":{"wt":"ref","href":"./Template:Ref"},"params":{"1":{"wt":"Ne Zha 2"},"2":{"wt":"NZ"}},"i":0}}]}' id="ref_Ne_Zha_2" typeof="mw:Transclusion"><a class="mw-selflink-fragment" href="#endnote_Ne_Zha_2" rel="mw:WikiLink">NZ</a></sup>$<span about="#mwt83" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:&lt;!--BOM TOTAL--&gt;2270700370-&lt;!--INCORRECT CHINA GROSS--&gt;2209602296+&lt;!--CORRECT CHINA GROSS--&gt;2155690000+&lt;!--INITIAL NEW ZEALAND GROSS--&gt;970308}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwATA" typeof="mw:Transclusion">2,217,758,382</span><!-- NOTE: DO NOT "fix" the gross for Ne Zha 2. The figure at Box Office Mojo is provably incorrect, so an alternative source is been used. --></td>
<td data-sort-value="2025-01" id="mwATE">2025</td>
<td id="mwATI"><sup about="#mwt87" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Ne Zha 2","group":"#"},"body":{"id":"mw-reference-text-cite_note-Ne_Zha_2-22"}}' id="cite_ref-Ne_Zha_2_22-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-Ne_Zha_2-22" id="mwATM"><span class="mw-reflink-text" id="mwATQ"><span class="cite-bracket" id="mwATU">[</span># 10<span class="cite-bracket" id="mwATY">]</span></span></a></sup><sup about="#mwt90" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Ne Zha 2 BOM","group":"#"},"body":{"id":"mw-reference-text-cite_note-Ne_Zha_2_BOM-23"}}' id="cite_ref-Ne_Zha_2_BOM_23-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-Ne_Zha_2_BOM-23" id="mwATc"><span class="mw-reflink-text" id="mwATg"><span class="cite-bracket" id="mwATk">[</span># 11<span class="cite-bracket" id="mwATo">]</span></span></a></sup></td></tr>
<tr id="mwATs">
<td id="mwATw">7</td>
<td id="mwAT0">3</td>
<th id="mwAT4" scope="row"><i id="mwAT8"><a href="https://en.wikipedia.org/wiki/Star_Wars:_The_Force_Awakens" id="mwAUA" rel="mw:WikiLink" title="Star Wars: The Force Awakens">Star Wars: The Force Awakens</a></i></th>
<td id="mwAUE">$2,068,223,624</td>
<td data-sort-value="2015-12" id="mwAUI">2015</td>
<td id="mwAUM"><sup about="#mwt93" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"sw7","group":"#"},"body":{"id":"mw-reference-text-cite_note-sw7-24"}}' id="cite_ref-sw7_24-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-sw7-24" id="mwAUQ"><span class="mw-reflink-text" id="mwAUU"><span class="cite-bracket" id="mwAUY">[</span># 12<span class="cite-bracket" id="mwAUc">]</span></span></a></sup><sup about="#mwt96" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"sw7 peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-sw7_peak-25"}}' id="cite_ref-sw7_peak_25-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-sw7_peak-25" id="mwAUg"><span class="mw-reflink-text" id="mwAUk"><span class="cite-bracket" id="mwAUo">[</span># 13<span class="cite-bracket" id="mwAUs">]</span></span></a></sup></td></tr>
<tr id="mwAUw">
<td id="mwAU0">8</td>
<td id="mwAU4">4</td>
<th id="mwAU8" scope="row"><i id="mwAVA"><a href="https://en.wikipedia.org/wiki/Avengers:_Infinity_War" id="mwAVE" rel="mw:WikiLink" title="Avengers: Infinity War">Avengers: Infinity War</a></i></th>
<td id="mwAVI">$2,048,359,754</td>
<td data-sort-value="2018-04" id="mwAVM">2018</td>
<td id="mwAVQ"><sup about="#mwt99" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"infinity war","group":"#"},"body":{"id":"mw-reference-text-cite_note-infinity_war-26"}}' id="cite_ref-infinity_war_26-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-infinity_war-26" id="mwAVU"><span class="mw-reflink-text" id="mwAVY"><span class="cite-bracket" id="mwAVc">[</span># 14<span class="cite-bracket" id="mwAVg">]</span></span></a></sup><sup about="#mwt102" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"infinity war peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-infinity_war_peak-27"}}' id="cite_ref-infinity_war_peak_27-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-infinity_war_peak-27" id="mwAVk"><span class="mw-reflink-text" id="mwAVo"><span class="cite-bracket" id="mwAVs">[</span># 15<span class="cite-bracket" id="mwAVw">]</span></span></a></sup></td></tr>
<tr id="mwAV0">
<td id="mwAV4">9</td>
<td id="mwAV8">6</td>
<th id="mwAWA" scope="row"><i id="mwAWE"><a href="https://en.wikipedia.org/wiki/Spider-Man:_No_Way_Home" id="mwAWI" rel="mw:WikiLink" title="Spider-Man: No Way Home">Spider-Man: No Way Home</a></i></th>
<td id="mwAWM"><sup about="#mwt103" class="plainlinks nourlexpansion citation" data-mw='{"parts":[{"template":{"target":{"wt":"ref","href":"./Template:Ref"},"params":{"1":{"wt":"Spider-Man"},"2":{"wt":"SM"}},"i":0}}]}' id="ref_Spider-Man" typeof="mw:Transclusion"><a class="mw-selflink-fragment" href="#endnote_Spider-Man" rel="mw:WikiLink">SM</a></sup>$1,922,598,800</td>
<td data-sort-value="2021-12" id="mwAWQ">2021</td>
<td id="mwAWU"><sup about="#mwt106" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"nwh","group":"#"},"body":{"id":"mw-reference-text-cite_note-nwh-28"}}' id="cite_ref-nwh_28-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-nwh-28" id="mwAWY"><span class="mw-reflink-text" id="mwAWc"><span class="cite-bracket" id="mwAWg">[</span># 16<span class="cite-bracket" id="mwAWk">]</span></span></a></sup><sup about="#mwt109" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"No Way Home peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-No_Way_Home_peak-29"}}' id="cite_ref-No_Way_Home_peak_29-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-No_Way_Home_peak-29" id="mwAWo"><span class="mw-reflink-text" id="mwAWs"><span class="cite-bracket" id="mwAWw">[</span># 17<span class="cite-bracket" id="mwAW0">]</span></span></a></sup></td></tr>
<tr id="mwAW4">
<td id="mwAW8">10</td>
<td id="mwAXA">9</td>
<th id="mwAXE" scope="row"><i id="mwAXI"><a href="https://en.wikipedia.org/wiki/Zootopia_2" id="mwAXM" rel="mw:WikiLink" title="Zootopia 2">Zootopia 2</a></i></th>
<td id="mwAXQ">$1,866,647,950<!-- DO NOT USE The Numbers instead of Box Office Mojo, BOM takes priority in the main table unless it is demonstrably wrong --></td>
<td data-sort-value="2025-11" id="mwAXU">2025</td>
<td id="mwAXY"><sup about="#mwt112" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"#"},"body":{"id":"mw-reference-text-cite_note-30"}}' id="cite_ref-30" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-30" id="mwAXc"><span class="mw-reflink-text" id="mwAXg"><span class="cite-bracket" id="mwAXk">[</span># 18<span class="cite-bracket" id="mwAXo">]</span></span></a></sup><sup about="#mwt115" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"zootopia 2 peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-zootopia_2_peak-31"}}' id="cite_ref-zootopia_2_peak_31-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-zootopia_2_peak-31" id="mwAXs"><span class="mw-reflink-text" id="mwAXw"><span class="cite-bracket" id="mwAX0">[</span># 19<span class="cite-bracket" id="mwAX4">]</span></span></a></sup></td></tr>
<tr id="mwAX8">
<td id="mwAYA">11</td>
<td id="mwAYE">11</td>
<th id="mwAYI" scope="row" style="background:#b6fcb6;"><span about="#mwt116" data-mw="{&quot;parts&quot;:[{&quot;template&quot;:{&quot;target&quot;:{&quot;wt&quot;:&quot;Sort&quot;,&quot;href&quot;:&quot;./Template:Sort&quot;},&quot;params&quot;:{&quot;1&quot;:{&quot;wt&quot;:&quot;Odyssey&quot;},&quot;2&quot;:{&quot;wt&quot;:&quot;''[[The Odyssey (2026 film)|The Odyssey]]'' †&quot;}},&quot;i&quot;:0}}]}" data-sort-value="Odyssey !" id="mwAYM" typeof="mw:Transclusion"><i><a href="https://en.wikipedia.org/wiki/The_Odyssey_(2026_film)" rel="mw:WikiLink" title="The Odyssey (2026 film)">The Odyssey</a></i> †</span></th>
<td id="mwAYQ">$1,725,495,324<!-- DO NOT USE The Numbers instead of Box Office Mojo, BOM takes priority in the main table unless it is demonstrably wrong --></td>
<td data-sort-value="2026-07" id="mwAYU">2026</td>
<td id="mwAYY"><sup about="#mwt119" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"#"},"body":{"id":"mw-reference-text-cite_note-32"}}' id="cite_ref-32" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-32" id="mwAYc"><span class="mw-reflink-text" id="mwAYg"><span class="cite-bracket" id="mwAYk">[</span># 20<span class="cite-bracket" id="mwAYo">]</span></span></a></sup></td></tr>
<tr id="mwAYs">
<td id="mwAYw">12</td>
<td id="mwAY0">8</td>
<th id="mwAY4" scope="row"><i id="mwAY8"><a href="https://en.wikipedia.org/wiki/Inside_Out_2" id="mwAZA" rel="mw:WikiLink" title="Inside Out 2">Inside Out 2</a></i></th>
<td id="mwAZE">$1,698,863,816</td>
<td data-sort-value="2024-06" id="mwAZI">2024</td>
<td id="mwAZM"><sup about="#mwt122" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Inside Out 2","group":"#"},"body":{"id":"mw-reference-text-cite_note-Inside_Out_2-33"}}' id="cite_ref-Inside_Out_2_33-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-Inside_Out_2-33" id="mwAZQ"><span class="mw-reflink-text" id="mwAZU"><span class="cite-bracket" id="mwAZY">[</span># 21<span class="cite-bracket" id="mwAZc">]</span></span></a></sup><sup about="#mwt125" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"inside out 2 peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-inside_out_2_peak-34"}}' id="cite_ref-inside_out_2_peak_34-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-inside_out_2_peak-34" id="mwAZg"><span class="mw-reflink-text" id="mwAZk"><span class="cite-bracket" id="mwAZo">[</span># 22<span class="cite-bracket" id="mwAZs">]</span></span></a></sup></td></tr>
<tr id="mwAZw">
<td id="mwAZ0">13</td>
<td id="mwAZ4">3</td>
<th id="mwAZ8" scope="row"><i id="mwAaA"><a href="https://en.wikipedia.org/wiki/Jurassic_World" id="mwAaE" rel="mw:WikiLink" title="Jurassic World">Jurassic World</a></i></th>
<td id="mwAaI">$1,671,537,444</td>
<td data-sort-value="2015-06" id="mwAaM">2015</td>

In [ ]:
table=soup.find('table',class_="wikitable sortable plainrowheaders sticky-header col4right col5center col6center")
table

<table class="wikitable sortable plainrowheaders sticky-header col4right col5center col6center" id="mwxg">
<caption id="mwxw">Highest-grossing films<sup about="#mwt53" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-12"}}' id="cite_ref-12" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-12" id="mwyA"><span class="mw-reflink-text" id="mwyQ"><span class="cite-bracket" id="mwyg">[</span>12<span class="cite-bracket" id="mwyw">]</span></span></a></sup></caption>
<!--When using "data&#x2D;sort&#x2D;value" use the first release date, not the U.S. one.-->
<tbody id="mwzA"><tr id="mwzQ"><th id="mwzg">Rank</th>
<th id="mwzw">Peak</th>
<th class="unsortable" id="mw0A">Title</th>
<th class="unsortable" id="mw0Q">Worldwide gross</th>
<th id="mw0g">Year</th>
<th class="unsortable" id="mw0w"><abbr about="#mwt54" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mw1A\"&gt;References&lt;/span&gt;"}]],"parts":[{"template":{"target":{"wt":"abbr","href":"./Template:Abbr"},"params":{"1":{"wt":"Ref"},"2":{"wt":"References"}},"i":0}}]}' id="mw1Q" title="References" typeof="mw:Transclusion mw:ExpandedAttrs">Ref</abbr></th></tr>
<tr id="mw1g"><!-- This is an international chart and the film may still be on its theater run outside the U.S. even after its U.S. home video release. The highlighting alerts readers and editors to the fact that its gross is still being updated. Please do not remove the highlight too early -->
<td id="mw1w">1</td>
<td id="mw2A">1</td>
<th id="mw2Q" scope="row"><i id="mw2g"><a href="https://en.wikipedia.org/wiki/Avatar_(2009_film)" id="mw2w" rel="mw:WikiLink" title="Avatar (2009 film)">Avatar</a></i></th>
<td id="mw3A">$2,923,710,708</td>
<td id="mw3Q">2009</td>
<td id="mw3g"><sup about="#mwt56" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"#","name":"avatar"}}' id="cite_ref-avatar_13-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-avatar-13" id="mw3w"><span class="mw-reflink-text" id="mw4A"><span class="cite-bracket" id="mw4Q">[</span># 1<span class="cite-bracket" id="mw4g">]</span></span></a></sup><sup about="#mwt59" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"avatar peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-avatar_peak-14"}}' id="cite_ref-avatar_peak_14-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-avatar_peak-14" id="mw4w"><span class="mw-reflink-text" id="mw5A"><span class="cite-bracket" id="mw5Q">[</span># 2<span class="cite-bracket" id="mw5g">]</span></span></a></sup></td></tr>
<tr id="mw5w">
<td id="mw6A">2</td>
<td id="mw6Q">1</td>
<th id="mw6g" scope="row" style="background:#b6fcb6;"><i id="mw6w"><a href="https://en.wikipedia.org/wiki/Avengers:_Endgame" id="mw7A" rel="mw:WikiLink" title="Avengers: Endgame">Avengers: Endgame</a></i> †</th>
<td id="mw7Q">$<span about="#mwt60" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:2797501328+&lt;!--ENCORE--&gt;0}}","function":"formatnum"},"params":{},"i":0}}]}' id="mw7g" typeof="mw:Transclusion">2,797,501,328</span><!-- NOTE: DO NOT "fix" the gross for Endgame, PER [[WP:BOXOFFICE]]. --></td>
<td data-sort-value="2019-04" id="mw7w">2019</td>
<td id="mw8A"><sup about="#mwt64" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"endgame","group":"#"},"body":{"id":"mw-reference-text-cite_note-endgame-15"}}' id="cite_ref-endgame_15-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-endgame-15" id="mw8Q"><span class="mw-reflink-text" id="mw8g"><span class="cite-bracket" id="mw8w">[</span># 3<span class="cite-bracket" id="mw9A">]</span></span></a></sup><sup about="#mwt67" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"endgame peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-endgame_peak-16"}}' id="cite_ref-endgame_peak_16-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-endgame_peak-16" id="mw9Q"><span class="mw-reflink-text" id="mw9g"><span class="cite-bracket" id="mw9w">[</span># 4<span class="cite-bracket" id="mw-A">]</span></span></a></sup></td></tr>
<tr id="mw-Q">
<td id="mw-g">3</td>
<td id="mw-w">3</td>
<th id="mw_A" scope="row" style="background:#b6fcb6;"><i id="mw_Q"><a href="https://en.wikipedia.org/wiki/Spider-Man:_Brand_New_Day" id="mw_g" rel="mw:WikiLink" title="Spider-Man: Brand New Day">Spider-Man: Brand New Day</a></i> †</th>
<td id="mw_w">$2,479,827,325<!-- DO NOT USE The Numbers instead of Box Office Mojo, BOM takes priority in the main table unless it is demonstrably wrong --></td>
<td data-sort-value="2026-07" id="mwAQA">2026</td>
<td id="mwAQE"><sup about="#mwt70" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"bnd","group":"#"},"body":{"id":"mw-reference-text-cite_note-bnd-17"}}' id="cite_ref-bnd_17-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-bnd-17" id="mwAQI"><span class="mw-reflink-text" id="mwAQM"><span class="cite-bracket" id="mwAQQ">[</span># 5<span class="cite-bracket" id="mwAQU">]</span></span></a></sup></td></tr>
<tr id="mwAQY">
<td id="mwAQc">4</td>
<td id="mwAQg">3</td>
<th id="mwAQk" scope="row"><i id="mwAQo"><a href="https://en.wikipedia.org/wiki/Avatar:_The_Way_of_Water" id="mwAQs" rel="mw:WikiLink" title="Avatar: The Way of Water">Avatar: The Way of Water</a></i></th>
<td id="mwAQw">$2,334,484,620</td>
<td data-sort-value="2022-12" id="mwAQ0">2022</td>
<td id="mwAQ4"><sup about="#mwt71" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"avatar2","group":"#"}}' id="cite_ref-avatar2_18-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-avatar2-18" id="mwAQ8"><span class="mw-reflink-text" id="mwARA"><span class="cite-bracket" id="mwARE">[</span># 6<span class="cite-bracket" id="mwARI">]</span></span></a></sup><sup about="#mwt74" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"avatar 2 peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-avatar_2_peak-19"}}' id="cite_ref-avatar_2_peak_19-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-avatar_2_peak-19" id="mwARM"><span class="mw-reflink-text" id="mwARQ"><span class="cite-bracket" id="mwARU">[</span># 7<span class="cite-bracket" id="mwARY">]</span></span></a></sup></td></tr>
<tr id="mwARc">
<td id="mwARg">5</td>
<td id="mwARk">1</td>
<th id="mwARo" scope="row"><i id="mwARs"><a href="https://en.wikipedia.org/wiki/Titanic_(1997_film)" id="mwARw" rel="mw:WikiLink" title="Titanic (1997 film)">Titanic</a></i></th>
<td id="mwAR0"><sup about="#mwt75" class="plainlinks nourlexpansion citation" data-mw='{"parts":[{"template":{"target":{"wt":"ref","href":"./Template:Ref"},"params":{"1":{"wt":"Titanic"},"2":{"wt":"T"}},"i":0}}]}' id="ref_Titanic" typeof="mw:Transclusion"><a class="mw-selflink-fragment" href="#endnote_Titanic" rel="mw:WikiLink">T</a></sup>$<span about="#mwt76" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:1843373318+343550770+691642+71352+70219746}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwAR4" typeof="mw:Transclusion">2,257,906,828</span><!-- NOTE: DO NOT "fix" the gross for Titanic. BOM is double&#x2D;counting in the 2012 3D gross. See archived citation for correct amounts. --></td>
<td id="mwAR8">1997</td>
<td id="mwASA"><sup about="#mwt78" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"#","name":"titanic"}}' id="cite_ref-titanic_20-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-titanic-20" id="mwASE"><span class="mw-reflink-text" id="mwASI"><span class="cite-bracket" id="mwASM">[</span># 8<span class="cite-bracket" id="mwASQ">]</span></span></a></sup><sup about="#mwt81" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"titanic peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-titanic_peak-21"}}' id="cite_ref-titanic_peak_21-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-titanic_peak-21" id="mwASU"><span class="mw-reflink-text" id="mwASY"><span class="cite-bracket" id="mwASc">[</span># 9<span class="cite-bracket" id="mwASg">]</span></span></a></sup></td></tr>
<tr id="mwASk">
<td id="mwASo">6</td>
<td id="mwASs">5</td>
<th id="mwASw" scope="row"><i id="mwAS0"><a href="https://en.wikipedia.org/wiki/Ne_Zha_2" id="mwAS4" rel="mw:WikiLink" title="Ne Zha 2">Ne Zha 2</a></i></th>
<td id="mwAS8"><sup about="#mwt82" class="plainlinks nourlexpansion citation" data-mw='{"parts":[{"template":{"target":{"wt":"ref","href":"./Template:Ref"},"params":{"1":{"wt":"Ne Zha 2"},"2":{"wt":"NZ"}},"i":0}}]}' id="ref_Ne_Zha_2" typeof="mw:Transclusion"><a class="mw-selflink-fragment" href="#endnote_Ne_Zha_2" rel="mw:WikiLink">NZ</a></sup>$<span about="#mwt83" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:&lt;!--BOM TOTAL--&gt;2270700370-&lt;!--INCORRECT CHINA GROSS--&gt;2209602296+&lt;!--CORRECT CHINA GROSS--&gt;2155690000+&lt;!--INITIAL NEW ZEALAND GROSS--&gt;970308}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwATA" typeof="mw:Transclusion">2,217,758,382</span><!-- NOTE: DO NOT "fix" the gross for Ne Zha 2. The figure at Box Office Mojo is provably incorrect, so an alternative source is been used. --></td>
<td data-sort-value="2025-01" id="mwATE">2025</td>
<td id="mwATI"><sup about="#mwt87" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Ne Zha 2","group":"#"},"body":{"id":"mw-reference-text-cite_note-Ne_Zha_2-22"}}' id="cite_ref-Ne_Zha_2_22-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-Ne_Zha_2-22" id="mwATM"><span class="mw-reflink-text" id="mwATQ"><span class="cite-bracket" id="mwATU">[</span># 10<span class="cite-bracket" id="mwATY">]</span></span></a></sup><sup about="#mwt90" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Ne Zha 2 BOM","group":"#"},"body":{"id":"mw-reference-text-cite_note-Ne_Zha_2_BOM-23"}}' id="cite_ref-Ne_Zha_2_BOM_23-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-Ne_Zha_2_BOM-23" id="mwATc"><span class="mw-reflink-text" id="mwATg"><span class="cite-bracket" id="mwATk">[</span># 11<span class="cite-bracket" id="mwATo">]</span></span></a></sup></td></tr>
<tr id="mwATs">
<td id="mwATw">7</td>
<td id="mwAT0">3</td>
<th id="mwAT4" scope="row"><i id="mwAT8"><a href="https://en.wikipedia.org/wiki/Star_Wars:_The_Force_Awakens" id="mwAUA" rel="mw:WikiLink" title="Star Wars: The Force Awakens">Star Wars: The Force Awakens</a></i></th>
<td id="mwAUE">$2,068,223,624</td>
<td data-sort-value="2015-12" id="mwAUI">2015</td>
<td id="mwAUM"><sup about="#mwt93" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"sw7","group":"#"},"body":{"id":"mw-reference-text-cite_note-sw7-24"}}' id="cite_ref-sw7_24-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-sw7-24" id="mwAUQ"><span class="mw-reflink-text" id="mwAUU"><span class="cite-bracket" id="mwAUY">[</span># 12<span class="cite-bracket" id="mwAUc">]</span></span></a></sup><sup about="#mwt96" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"sw7 peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-sw7_peak-25"}}' id="cite_ref-sw7_peak_25-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-sw7_peak-25" id="mwAUg"><span class="mw-reflink-text" id="mwAUk"><span class="cite-bracket" id="mwAUo">[</span># 13<span class="cite-bracket" id="mwAUs">]</span></span></a></sup></td></tr>
<tr id="mwAUw">
<td id="mwAU0">8</td>
<td id="mwAU4">4</td>
<th id="mwAU8" scope="row"><i id="mwAVA"><a href="https://en.wikipedia.org/wiki/Avengers:_Infinity_War" id="mwAVE" rel="mw:WikiLink" title="Avengers: Infinity War">Avengers: Infinity War</a></i></th>
<td id="mwAVI">$2,048,359,754</td>
<td data-sort-value="2018-04" id="mwAVM">2018</td>
<td id="mwAVQ"><sup about="#mwt99" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"infinity war","group":"#"},"body":{"id":"mw-reference-text-cite_note-infinity_war-26"}}' id="cite_ref-infinity_war_26-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-infinity_war-26" id="mwAVU"><span class="mw-reflink-text" id="mwAVY"><span class="cite-bracket" id="mwAVc">[</span># 14<span class="cite-bracket" id="mwAVg">]</span></span></a></sup><sup about="#mwt102" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"infinity war peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-infinity_war_peak-27"}}' id="cite_ref-infinity_war_peak_27-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-infinity_war_peak-27" id="mwAVk"><span class="mw-reflink-text" id="mwAVo"><span class="cite-bracket" id="mwAVs">[</span># 15<span class="cite-bracket" id="mwAVw">]</span></span></a></sup></td></tr>
<tr id="mwAV0">
<td id="mwAV4">9</td>
<td id="mwAV8">6</td>
<th id="mwAWA" scope="row"><i id="mwAWE"><a href="https://en.wikipedia.org/wiki/Spider-Man:_No_Way_Home" id="mwAWI" rel="mw:WikiLink" title="Spider-Man: No Way Home">Spider-Man: No Way Home</a></i></th>
<td id="mwAWM"><sup about="#mwt103" class="plainlinks nourlexpansion citation" data-mw='{"parts":[{"template":{"target":{"wt":"ref","href":"./Template:Ref"},"params":{"1":{"wt":"Spider-Man"},"2":{"wt":"SM"}},"i":0}}]}' id="ref_Spider-Man" typeof="mw:Transclusion"><a class="mw-selflink-fragment" href="#endnote_Spider-Man" rel="mw:WikiLink">SM</a></sup>$1,922,598,800</td>
<td data-sort-value="2021-12" id="mwAWQ">2021</td>
<td id="mwAWU"><sup about="#mwt106" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"nwh","group":"#"},"body":{"id":"mw-reference-text-cite_note-nwh-28"}}' id="cite_ref-nwh_28-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-nwh-28" id="mwAWY"><span class="mw-reflink-text" id="mwAWc"><span class="cite-bracket" id="mwAWg">[</span># 16<span class="cite-bracket" id="mwAWk">]</span></span></a></sup><sup about="#mwt109" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"No Way Home peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-No_Way_Home_peak-29"}}' id="cite_ref-No_Way_Home_peak_29-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-No_Way_Home_peak-29" id="mwAWo"><span class="mw-reflink-text" id="mwAWs"><span class="cite-bracket" id="mwAWw">[</span># 17<span class="cite-bracket" id="mwAW0">]</span></span></a></sup></td></tr>
<tr id="mwAW4">
<td id="mwAW8">10</td>
<td id="mwAXA">9</td>
<th id="mwAXE" scope="row"><i id="mwAXI"><a href="https://en.wikipedia.org/wiki/Zootopia_2" id="mwAXM" rel="mw:WikiLink" title="Zootopia 2">Zootopia 2</a></i></th>
<td id="mwAXQ">$1,866,647,950<!-- DO NOT USE The Numbers instead of Box Office Mojo, BOM takes priority in the main table unless it is demonstrably wrong --></td>
<td data-sort-value="2025-11" id="mwAXU">2025</td>
<td id="mwAXY"><sup about="#mwt112" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"#"},"body":{"id":"mw-reference-text-cite_note-30"}}' id="cite_ref-30" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-30" id="mwAXc"><span class="mw-reflink-text" id="mwAXg"><span class="cite-bracket" id="mwAXk">[</span># 18<span class="cite-bracket" id="mwAXo">]</span></span></a></sup><sup about="#mwt115" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"zootopia 2 peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-zootopia_2_peak-31"}}' id="cite_ref-zootopia_2_peak_31-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-zootopia_2_peak-31" id="mwAXs"><span class="mw-reflink-text" id="mwAXw"><span class="cite-bracket" id="mwAX0">[</span># 19<span class="cite-bracket" id="mwAX4">]</span></span></a></sup></td></tr>
<tr id="mwAX8">
<td id="mwAYA">11</td>
<td id="mwAYE">11</td>
<th id="mwAYI" scope="row" style="background:#b6fcb6;"><span about="#mwt116" data-mw="{&quot;parts&quot;:[{&quot;template&quot;:{&quot;target&quot;:{&quot;wt&quot;:&quot;Sort&quot;,&quot;href&quot;:&quot;./Template:Sort&quot;},&quot;params&quot;:{&quot;1&quot;:{&quot;wt&quot;:&quot;Odyssey&quot;},&quot;2&quot;:{&quot;wt&quot;:&quot;''[[The Odyssey (2026 film)|The Odyssey]]'' †&quot;}},&quot;i&quot;:0}}]}" data-sort-value="Odyssey !" id="mwAYM" typeof="mw:Transclusion"><i><a href="https://en.wikipedia.org/wiki/The_Odyssey_(2026_film)" rel="mw:WikiLink" title="The Odyssey (2026 film)">The Odyssey</a></i> †</span></th>
<td id="mwAYQ">$1,725,495,324<!-- DO NOT USE The Numbers instead of Box Office Mojo, BOM takes priority in the main table unless it is demonstrably wrong --></td>
<td data-sort-value="2026-07" id="mwAYU">2026</td>
<td id="mwAYY"><sup about="#mwt119" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"#"},"body":{"id":"mw-reference-text-cite_note-32"}}' id="cite_ref-32" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-32" id="mwAYc"><span class="mw-reflink-text" id="mwAYg"><span class="cite-bracket" id="mwAYk">[</span># 20<span class="cite-bracket" id="mwAYo">]</span></span></a></sup></td></tr>
<tr id="mwAYs">
<td id="mwAYw">12</td>
<td id="mwAY0">8</td>
<th id="mwAY4" scope="row"><i id="mwAY8"><a href="https://en.wikipedia.org/wiki/Inside_Out_2" id="mwAZA" rel="mw:WikiLink" title="Inside Out 2">Inside Out 2</a></i></th>
<td id="mwAZE">$1,698,863,816</td>
<td data-sort-value="2024-06" id="mwAZI">2024</td>
<td id="mwAZM"><sup about="#mwt122" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Inside Out 2","group":"#"},"body":{"id":"mw-reference-text-cite_note-Inside_Out_2-33"}}' id="cite_ref-Inside_Out_2_33-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-Inside_Out_2-33" id="mwAZQ"><span class="mw-reflink-text" id="mwAZU"><span class="cite-bracket" id="mwAZY">[</span># 21<span class="cite-bracket" id="mwAZc">]</span></span></a></sup><sup about="#mwt125" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"inside out 2 peak","group":"#"},"body":{"id":"mw-reference-text-cite_note-inside_out_2_peak-34"}}' id="cite_ref-inside_out_2_peak_34-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="#" href="#cite_note-inside_out_2_peak-34" id="mwAZg"><span class="mw-reflink-text" id="mwAZk"><span class="cite-bracket" id="mwAZo">[</span># 22<span class="cite-bracket" id="mwAZs">]</span></span></a></sup></td></tr>
<tr id="mwAZw">
<td id="mwAZ0">13</td>
<td id="mwAZ4">3</td>
<th id="mwAZ8" scope="row"><i id="mwAaA"><a href="https://en.wikipedia.org/wiki/Jurassic_World" id="mwAaE" rel="mw:WikiLink" title="Jurassic World">Jurassic World</a></i></th>
<td id="mwAaI">$1,671,537,444</td>
<td data-sort-value="2015-06" id="mwAaM">2015</td>

In [ ]:
table1=soup.find('table',id='mwBME')
table1

<table class="wikitable plainrowheaders sticky-header col3right col4center" id="mwBME">
<caption id="mwBMI"><span about="#mwt473" class="nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"nowrap","href":"./Template:Nowrap"},"params":{"1":{"wt":"Highest-grossing films {{As of|2025|lc=y}} adjusted for inflation&lt;ref name=\"Guinness 2015\"&gt;{{cite book |title=Guinness World Records |edition=2015 |year=2014 |volume=60 |isbn=978-1-908843-70-8 |pages=160–161 |publisher=Guinness World Records}}&lt;/ref&gt;{{ref label|Inflation|Inf}}"}},"i":0}}]}' id="mwBMM" typeof="mw:Transclusion">Highest-grossing films as of 2025<sup class="plainlinks noexcerpt noprint asof-tag update" style="display:none;"><a class="external text" data-mw-original-href="//en.wikipedia.org/w/index.php?title=List_of_highest-grossing_films&amp;action=edit" href="https://en.wikipedia.org/w/index.php?title=List_of_highest-grossing_films&amp;action=edit" rel="mw:ExtLink"><span typeof="mw:Entity">[</span>update<span typeof="mw:Entity">]</span></a></sup><link href="./Category:Articles_containing_potentially_dated_statements_from_2025" rel="mw:PageProp/Category"/><link href="./Category:All_articles_containing_potentially_dated_statements" rel="mw:PageProp/Category"/> adjusted for inflation<sup about="#mwt476" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Guinness 2015"},"body":{"id":"mw-reference-text-cite_note-Guinness_2015-122"}}' id="cite_ref-Guinness_2015_122-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-Guinness_2015-122" id="mwBMQ"><span class="mw-reflink-text" id="mwBMU"><span class="cite-bracket" id="mwBMY">[</span>37<span class="cite-bracket" id="mwBMc">]</span></span></a></sup><link about="#mwt479" data-mw='{"name":"templatestyles","attrs":{"src":"Citation/styles.css"}}' href="mw-data:TemplateStyles:r1041539562" rel="mw-deduplicated-inline-style" typeof="mw:Extension/templatestyles"/><sup class="citation nobold" id="ref_Inflation"><a class="mw-selflink-fragment" href="#endnote_Inflation" rel="mw:WikiLink">[Inf]</a></sup></span></caption>
<tbody id="mwBMg"><tr id="mwBMk"><th id="mwBMo" scope="col">Rank</th>
<th id="mwBMs" scope="col">Title</th>
<th data-sort-type="currency" id="mwBMw" scope="col"><div about="#mwt480" data-mw='{"parts":[{"template":{"target":{"wt":"longitem","href":"./Template:Longitem"},"params":{"1":{"wt":"Worldwide gross&lt;br /&gt;{{small|(2025 $)}}"}},"i":0}}]}' id="mwBM0" style="display: inline-block; line-height: 1.2em; padding: .1em 0; " typeof="mw:Transclusion">Worldwide gross<br/><span style="font-size: 85%;">(2025 $)</span></div></th>
<th id="mwBM4" scope="col">Year</th></tr>
<tr id="mwBM8">
<td id="mwBNA">1</td>
<th id="mwBNE" scope="row"><i id="mwBNI"><a href="https://en.wikipedia.org/wiki/Gone_with_the_Wind_(film)" id="mwBNM" rel="mw:WikiLink" title="Gone with the Wind (film)">Gone with the Wind</a></i></th>
<td id="mwBNQ"><sup about="#mwt481" class="plainlinks nourlexpansion citation" data-mw='{"parts":[{"template":{"target":{"wt":"ref ","href":"./Template:Ref"},"params":{"1":{"wt":"GWTW"},"2":{"wt":"GW"}},"i":0}}]}' id="ref_GWTW" typeof="mw:Transclusion"><a class="mw-selflink-fragment" href="#endnote_GWTW" rel="mw:WikiLink">GW</a></sup>$<span about="#mwt482" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:(&lt;!--2013--&gt;3440000000&lt;!--2014--&gt;*1.007&lt;!--2015--&gt;*1.005&lt;!--2016--&gt;*1.015&lt;!--2017--&gt;*1.017&lt;!--2018--&gt;*1.016&lt;!--2019--&gt;*1.015+2176120)&lt;!--2020--&gt;*1.005&lt;!--2021--&gt;*1.053&lt;!--2022--&gt;*1.073&lt;!--2023--&gt;*1.031&lt;!--2024--&gt;*1.025&lt;!--2025--&gt;*1.025 round -6}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwBNU" typeof="mw:Transclusion">4,561,000,000</span></td>
<td id="mwBNY">1939</td></tr>
<tr id="mwBNc">
<td id="mwBNg">2</td>
<th id="mwBNk" scope="row"><i id="mwBNo"><a href="https://en.wikipedia.org/wiki/Avatar_(2009_film)" id="mwBNs" rel="mw:WikiLink" title="Avatar (2009 film)">Avatar</a></i></th>
<td id="mwBNw"><sup about="#mwt484" class="plainlinks nourlexpansion citation" data-mw='{"parts":[{"template":{"target":{"wt":"ref ","href":"./Template:Ref"},"params":{"1":{"wt":"Avatar"},"2":{"wt":"A1"}},"i":0}}]}' id="ref_Avatar" typeof="mw:Transclusion"><a class="mw-selflink-fragment" href="#endnote_Avatar" rel="mw:WikiLink">A1</a></sup>$<span about="#mwt485" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:((&lt;!--2013--&gt;3020000000&lt;!--2014--&gt;*1.007&lt;!--2015--&gt;*1.005&lt;!--2016--&gt;*1.015&lt;!--2017--&gt;*1.017&lt;!--2018--&gt;*1.017&lt;!--2019--&gt;*1.015&lt;!--2020--&gt;*1.005&lt;!--2021--&gt;*1.053+1281204+57995770)&lt;!--2022--&gt;*1.073+76012917)&lt;!--2023--&gt;*1.031&lt;!--2024--&gt;*1.025&lt;!--2025--&gt;*1.025 round -6}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwBN0" typeof="mw:Transclusion">4,157,000,000</span></td>
<td id="mwBN4">2009</td></tr>
<tr id="mwBN8">
<td id="mwBOA">3</td>
<th id="mwBOE" scope="row"><i id="mwBOI"><a href="https://en.wikipedia.org/wiki/Titanic_(1997_film)" id="mwBOM" rel="mw:WikiLink" title="Titanic (1997 film)">Titanic</a></i></th>
<td id="mwBOQ"><span id="mwBOU" style="display:none">$2,516,000,000</span><sup about="#mwt487" class="plainlinks nourlexpansion citation" data-mw='{"parts":[{"template":{"target":{"wt":"ref ","href":"./Template:Ref"},"params":{"1":{"wt":"Titanic"},"2":{"wt":"T"}},"i":0}}]}' data-x-id="ref_Titanic" id="mwBOY" typeof="mw:Transclusion"><a class="mw-selflink-fragment" href="#endnote_Titanic" rel="mw:WikiLink">T</a></sup>$<span about="#mwt488" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:((&lt;!--2013--&gt;2516000000+&lt;!--2012 REISSUE--&gt;57884114+285666656)&lt;!--2014--&gt;*1.007&lt;!--2015--&gt;*1.005&lt;!--2016--&gt;*1.015&lt;!--2017--&gt;*1.017&lt;!--2018--&gt;*1.016&lt;!--2019--&gt;*1.015&lt;!--2020--&gt;*1.005&lt;!--2021--&gt;*1.053&lt;!--2022--&gt;*1.073&lt;!--2023--&gt;*1.031+691642+78741+70157472)&lt;!--2024--&gt;*1.025&lt;!--2025--&gt;*1.025 round -6}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwBOc" typeof="mw:Transclusion">3,864,000,000</span></td>
<td id="mwBOg">1997</td></tr>
<tr id="mwBOk">
<td id="mwBOo">4</td>
<th id="mwBOs" scope="row"><i id="mwBOw"><a href="https://en.wikipedia.org/wiki/Star_Wars_(film)" id="mwBO0" rel="mw:WikiLink" title="Star Wars (film)">Star Wars</a></i></th>
<td id="mwBO4">$<span about="#mwt490" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:&lt;!--2013--&gt;2825000000&lt;!--2014--&gt;*1.007&lt;!--2015--&gt;*1.005&lt;!--2016--&gt;*1.015&lt;!--2017--&gt;*1.017&lt;!--2018--&gt;*1.016&lt;!--2019--&gt;*1.015&lt;!--2020--&gt;*1.005&lt;!--2021--&gt;*1.053&lt;!--2022--&gt;*1.073&lt;!--2023--&gt;*1.031&lt;!--2024--&gt;*1.025&lt;!--2025--&gt;*1.025 round -6}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwBO8" typeof="mw:Transclusion">3,743,000,000</span></td>
<td id="mwBPA">1977</td></tr>
<tr id="mwBPE">
<td id="mwBPI">5</td>
<th id="mwBPM" scope="row"><i id="mwBPQ"><a href="https://en.wikipedia.org/wiki/Avengers:_Endgame" id="mwBPU" rel="mw:WikiLink" title="Avengers: Endgame">Avengers: Endgame</a></i></th>
<td id="mwBPY"><sup about="#mwt492" class="plainlinks nourlexpansion citation" data-mw='{"parts":[{"template":{"target":{"wt":"ref ","href":"./Template:Ref"},"params":{"1":{"wt":"Avengers Endgame"},"2":{"wt":"AE"}},"i":0}}]}' id="ref_Avengers_Endgame" typeof="mw:Transclusion"><a class="mw-selflink-fragment" href="#endnote_Avengers_Endgame" rel="mw:WikiLink">AE</a></sup>$<span about="#mwt493" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:&lt;!--2019--&gt;2797501328&lt;!--2020--&gt;*1.005&lt;!--2021--&gt;*1.053&lt;!--2022--&gt;*1.073&lt;!--2023--&gt;*1.031&lt;!--2024--&gt;*1.025&lt;!--2025--&gt;*1.025 round-6}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwBPc" typeof="mw:Transclusion">3,441,000,000</span></td>
<td id="mwBPg">2019</td></tr>
<tr id="mwBPk">
<td id="mwBPo">6</td>
<th id="mwBPs" scope="row"><i id="mwBPw"><a href="https://en.wikipedia.org/wiki/The_Sound_of_Music_(film)" id="mwBP0" rel="mw:WikiLink" title="The Sound of Music (film)">The Sound of Music</a></i></th>
<td id="mwBP4">$<span about="#mwt495" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:(&lt;!--2013--&gt;2366000000&lt;!--2014--&gt;*1.007&lt;!--2015--&gt;*1.005&lt;!--2016--&gt;*1.015&lt;!--2017--&gt;*1.017&lt;!--2018--&gt;*1.016&lt;!--2019--&gt;*1.015&lt;!--2020--&gt;*1.005&lt;!--2021--&gt;*1.053&lt;!--2022--&gt;*1.073&lt;!--2023--&gt;*1.031&lt;!--2024--&gt;*1.025)&lt;!--2025--&gt;*1.025+(10205+73754+25922+624392+7933+30301+9373+1960214) round -6}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwBP8" typeof="mw:Transclusion">3,138,000,000</span></td>
<td id="mwBQA">1965</td></tr>
<tr id="mwBQE">
<td id="mwBQI">7</td>
<th id="mwBQM" scope="row"><i id="mwBQQ"><a href="https://en.wikipedia.org/wiki/E.T._the_Extra-Terrestrial" id="mwBQU" rel="mw:WikiLink" title="E.T. the Extra-Terrestrial">E.T. the Extra-Terrestrial</a></i></th>
<td id="mwBQY"><sup about="#mwt497" class="plainlinks nourlexpansion citation" data-mw='{"parts":[{"template":{"target":{"wt":"ref ","href":"./Template:Ref"},"params":{"1":{"wt":"ET"},"2":{"wt":"ET"}},"i":0}}]}' id="ref_ET" typeof="mw:Transclusion"><a class="mw-selflink-fragment" href="#endnote_ET" rel="mw:WikiLink">ET</a></sup>$<span about="#mwt498" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:(&lt;!--2013--&gt;2310000000&lt;!--2014--&gt;*1.007&lt;!--2015--&gt;*1.005&lt;!--2016--&gt;*1.015&lt;!--2017--&gt;*1.017&lt;!--2018--&gt;*1.016&lt;!--2019--&gt;*1.015&lt;!--2020--&gt;*1.005&lt;!--2021--&gt;*1.053&lt;!--2022--&gt;*1.073+516969+2834590)&lt;!--2023--&gt;*1.031&lt;!--2024--&gt;*1.025&lt;!--2025--&gt;*1.025 round -6}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwBQc" typeof="mw:Transclusion">3,065,000,000</span></td>
<td id="mwBQg">1982</td></tr>
<tr id="mwBQk">
<td id="mwBQo">8</td>
<th id="mwBQs" scope="row"><i id="mwBQw"><a href="https://en.wikipedia.org/wiki/The_Ten_Commandments_(1956_film)" id="mwBQ0" rel="mw:WikiLink" title="The Ten Commandments (1956 film)">The Ten Commandments</a></i></th>
<td id="mwBQ4">$<span about="#mwt500" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:&lt;!--2013--&gt;2187000000&lt;!--2014--&gt;*1.007&lt;!--2015--&gt;*1.005&lt;!--2016--&gt;*1.015&lt;!--2017--&gt;*1.017&lt;!--2018--&gt;*1.016&lt;!--2019--&gt;*1.015&lt;!--2020--&gt;*1.005&lt;!--2021--&gt;*1.053&lt;!--2022--&gt;*1.073&lt;!--2023--&gt;*1.031&lt;!--2024--&gt;*1.025&lt;!--2025--&gt;*1.025 round -6}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwBQ8" typeof="mw:Transclusion">2,898,000,000</span></td>
<td id="mwBRA">1956</td></tr>
<tr id="mwBRE">
<td id="mwBRI">9</td>
<th id="mwBRM" scope="row"><i id="mwBRQ"><a href="https://en.wikipedia.org/wiki/Doctor_Zhivago_(film)" id="mwBRU" rel="mw:WikiLink" title="Doctor Zhivago (film)">Doctor Zhivago</a></i></th>
<td id="mwBRY">$<span about="#mwt502" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:&lt;!--2013--&gt;2073000000&lt;!--2014--&gt;*1.007&lt;!--2015--&gt;*1.005&lt;!--2016--&gt;*1.015&lt;!--2017--&gt;*1.017&lt;!--2018--&gt;*1.016&lt;!--2019--&gt;*1.015&lt;!--2020--&gt;*1.005&lt;!--2021--&gt;*1.053&lt;!--2022--&gt;*1.073&lt;!--2023--&gt;*1.031&lt;!--2024--&gt;*1.025&lt;!--2025--&gt;*1.025 round -6}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwBRc" typeof="mw:Transclusion">2,747,000,000</span></td>
<td id="mwBRg">1965</td></tr>
<tr id="mwBRk">
<td id="mwBRo">10</td>
<th id="mwBRs" scope="row"><i id="mwBRw"><a href="https://en.wikipedia.org/wiki/Jaws_(film)" id="mwBR0" rel="mw:WikiLink" title="Jaws (film)">Jaws</a></i></th>
<td id="mwBR4"><sup about="#mwt504" class="plainlinks nourlexpansion citation" data-mw='{"parts":[{"template":{"target":{"wt":"ref ","href":"./Template:Ref"},"params":{"1":{"wt":"Jaws"},"2":{"wt":"J"}},"i":0}}]}' id="ref_Jaws" typeof="mw:Transclusion"><a class="mw-selflink-fragment" href="#endnote_Jaws" rel="mw:WikiLink">J</a></sup>$<span about="#mwt505" data-mw='{"parts":[{"template":{"target":{"wt":"formatnum:{{#expr:(&lt;!--2013--&gt;2027000000&lt;!--2014--&gt;*1.007&lt;!--2015--&gt;*1.005&lt;!--2016--&gt;*1.015&lt;!--2017--&gt;*1.017&lt;!--2018--&gt;*1.016&lt;!--2019--&gt;*1.015&lt;!--2020--&gt;*1.005&lt;!--2021--&gt;*1.053&lt;!--2022--&gt;*1.073&lt;!--2023--&gt;*1.031&lt;!--2024--&gt;*1.025)&lt;!--2025--&gt;*1.025+507140+42864+790314+6358261+3642+16172364 round -5}}","function":"formatnum"},"params":{},"i":0}}]}' id="mwBR8" typeof="mw:Transclusion">2,709,800,000</span></td>
<td id="mwBSA">1975</td></tr>
</tbody></table>

In [ ]:
headers=table.find('tr').text
headers

'Rank\nPeak\nTitle\nWorldwide gross\nYear\nRef'

In [ ]:
headers1=table1.find('tr').text
headers1

'Rank\nTitle\nWorldwide gross(2025 $)\nYear'

In [ ]:
header=table.find('tr')
cols=[th.get_text(strip=True) for th in header if th.get_text(strip=True)]
cols

['Rank', 'Peak', 'Title', 'Worldwide gross', 'Year', 'Ref']

In [ ]:
trs=table.find_all('tr')[1:]
row_data=[]
for t_row in trs:
  row=[t_data.get_text(strip=True) for t_data in t_row.find_all(['td','th'])]
  row_data.append(row)
row_data

[['1', '1', 'Avatar', '$2,923,710,708', '2009', '[# 1][# 2]'],
 ['2', '1', 'Avengers: Endgame†', '$2,797,501,328', '2019', '[# 3][# 4]'],
 ['3', '3', 'Spider-Man: Brand New Day†', '$2,479,827,325', '2026', '[# 5]'],
 ['4',
  '3',
  'Avatar: The Way of Water',
  '$2,334,484,620',
  '2022',
  '[# 6][# 7]'],
 ['5', '1', 'Titanic', 'T$2,257,906,828', '1997', '[# 8][# 9]'],
 ['6', '5', 'Ne Zha 2', 'NZ$2,217,758,382', '2025', '[# 10][# 11]'],
 ['7',
  '3',
  'Star Wars: The Force Awakens',
  '$2,068,223,624',
  '2015',
  '[# 12][# 13]'],
 ['8',
  '4',
  'Avengers: Infinity War',
  '$2,048,359,754',
  '2018',
  '[# 14][# 15]'],
 ['9',
  '6',
  'Spider-Man: No Way Home',
  'SM$1,922,598,800',
  '2021',
  '[# 16][# 17]'],
 ['10', '9', 'Zootopia 2', '$1,866,647,950', '2025', '[# 18][# 19]'],
 ['11', '11', 'The Odyssey†', '$1,725,495,324', '2026', '[# 20]'],
 ['12', '8', 'Inside Out 2', '$1,698,863,816', '2024', '[# 21][# 22]'],
 ['13', '3', 'Jurassic World', '$1,671,537,444', '2015', '[# 23][# 24]'],
 ['14', '7', 'The Lion King', '$1,656,943,394', '2019', '[# 25][# 4]'],
 ['15', '3', 'The Avengers', '$1,518,815,515', '2012', '[# 26][# 27]'],
 ['16', '4', 'Furious 7', '$1,515,341,399', '2015', '[# 28][# 29]'],
 ['17', '11', 'Top Gun: Maverick', '$1,503,260,455', '2022', '[# 30][# 31]'],
 ['18',
  '16',
  'Avatar: Fire and Ash',
  '$1,485,999,890',
  '2025',
  '[# 32][# 33]'],
 ['19', '10', 'Frozen 2', '$1,450,026,933', '2019', '[# 34][# 35]'],
 ['20', '14', 'Barbie', '$1,447,138,421', '2023', '[# 36][# 37]'],
 ['21',
  '5',
  'Avengers: Age of Ultron',
  '$1,402,809,540',
  '2015',
  '[# 38][# 29]'],
 ['22',
  '15',
  'The Super Mario Bros. Movie',
  '$1,360,783,214',
  '2023',
  '[# 39][# 40]'],
 ['23', '9', 'Black Panther', '$1,347,280,838', '2018', '[# 41][# 42]'],
 ['24',
  '3',
  'Harry Potter and the Deathly Hallows – Part 2',
  '$1,342,139,727',
  '2011',
  '[# 43][# 44]'],
 ['25',
  '20',
  'Deadpool & Wolverine',
  '$1,338,073,645',
  '2024',
  '[# 45][# 46]'],
 ['26',
  '9',
  'Star Wars: The Last Jedi',
  '$1,332,539,889',
  '2017',
  '[# 47][# 48]'],
 ['27',
  '12',
  'Jurassic World: Fallen Kingdom',
  '$1,308,476,166',
  '2018',
  '[# 49][# 15]'],
 ['28', '5', 'Frozen', 'F$1,290,000,000', '2013', '[# 50][# 51]'],
 ['29',
  '10',
  'Beauty and the Beast',
  '$1,263,521,126',
  '2017',
  '[# 52][# 53]'],
 ['30', '15', 'Incredibles 2', '$1,242,805,359', '2018', '[# 54][# 15]'],
 ['31',
  '11',
  'The Fate of the Furious',
  'F8$1,238,764,765',
  '2017',
  '[# 55][# 53]'],
 ['32', '5', 'Iron Man 3', '$1,214,811,252', '2013', '[# 56][# 57]'],
 ['33', '10', 'Minions', '$1,159,444,662', '2015', '[# 58][# 24]'],
 ['34',
  '12',
  'Captain America: Civil War',
  '$1,153,337,496',
  '2016',
  '[# 59][# 60]'],
 ['35', '20', 'Aquaman', '$1,148,528,393', '2018', '[# 61][# 15]'],
 ['36',
  '2',
  'The Lord of the Rings: The Return of the King',
  '$1,147,997,407',
  '2003',
  '[# 62][# 63]'],
 ['37', '37', 'Toy Story 5†', '$1,146,073,398', '2026', '[# 64]'],
 ['38',
  '24RK',
  'Spider-Man: Far From Home',
  '$1,132,679,685',
  '2019',
  '[# 65][# 4]'],
 ['39', '23RK', 'Captain Marvel', '$1,128,274,794', '2019', '[# 66][# 67]'],
 ['40',
  '5RK',
  'Transformers: Dark of the Moon',
  '$1,123,794,079',
  '2011',
  '[# 68][# 44]'],
 ['41', '7', 'Skyfall', '$1,108,594,137', '2012', '[# 69][# 70]'],
 ['42',
  '10',
  'Transformers: Age of Extinction',
  '$1,104,054,072',
  '2014',
  '[# 71][# 72]'],
 ['43JP',
  '7',
  'The Dark Knight Rises',
  'DKR$1,081,169,825',
  '2012',
  '[# 73][# 74]'],
 ['44', '31', 'Joker', '$1,074,458,282', '2019', '[# 75][# 35]'],
 ['45',
  '32',
  'Star Wars: The Rise of Skywalker',
  '$1,074,144,248',
  '2019',
  '[# 76][# 35]'],
 ['46', '30', 'Toy Story 4', '$1,073,394,593', '2019', '[# 77][# 4]'],
 ['47', '4TS3', 'Toy Story 3', '$1,066,970,811', '2010', '[# 78][# 79]'],
 ['48',
  '3',
  "Pirates of the Caribbean: Dead Man's Chest",
  '$1,066,179,747',
  '2006',
  '[# 80][# 81]'],
 ['49', '44', 'Moana 2', '$1,059,242,164', '2024', '[# 82][# 83]'],
 ['50',
  '20',
  'Rogue One: A Star Wars Story',
  '$1,057,420,387',
  '2016',
  '[# 84][# 85]']]

In [ ]:
import pandas as pd
df=pd.DataFrame(row_data,columns=cols)
df

,Rank,Peak,Title,Worldwide gross,Year,Ref
0,1,1,Avatar,"$2,923,710,708",2009,[# 1][# 2]
1,2,1,Avengers: Endgame†,"$2,797,501,328",2019,[# 3][# 4]
2,3,3,Spider-Man: Brand New Day†,"$2,479,827,325",2026,[# 5]
3,4,3,Avatar: The Way of Water,"$2,334,484,620",2022,[# 6][# 7]
4,5,1,Titanic,"T$2,257,906,828",1997,[# 8][# 9]
5,6,5,Ne Zha 2,"NZ$2,217,758,382",2025,[# 10][# 11]
6,7,3,Star Wars: The Force Awakens,"$2,068,223,624",2015,[# 12][# 13]
7,8,4,Avengers: Infinity War,"$2,048,359,754",2018,[# 14][# 15]
8,9,6,Spider-Man: No Way Home,"SM$1,922,598,800",2021,[# 16][# 17]
9,10,9,Zootopia 2,"$1,866,647,950",2025,[# 18][# 19]
10,11,11,The Odyssey†,"$1,725,495,324",2026,[# 20]
11,12,8,Inside Out 2,"$1,698,863,816",2024,[# 21][# 22]
12,13,3,Jurassic World,"$1,671,537,444",2015,[# 23][# 24]
13,14,7,The Lion King,"$1,656,943,394",2019,[# 25][# 4]
14,15,3,The Avengers,"$1,518,815,515",2012,[# 26][# 27]
15,16,4,Furious 7,"$1,515,341,399",2015,[# 28][# 29]
16,17,11,Top Gun: Maverick,"$1,503,260,455",2022,[# 30][# 31]
17,18,16,Avatar: Fire and Ash,"$1,485,999,890",2025,[# 32][# 33]
18,19,10,Frozen 2,"$1,450,026,933",2019,[# 34][# 35]
19,20,14,Barbie,"$1,447,138,421",2023,[# 36][# 37]
20,21,5,Avengers: Age of Ultron,"$1,402,809,540",2015,[# 38][# 29]
21,22,15,The Super Mario Bros. Movie,"$1,360,783,214",2023,[# 39][# 40]
22,23,9,Black Panther,"$1,347,280,838",2018,[# 41][# 42]
23,24,3,Harry Potter and the Deathly Hallows – Part 2,"$1,342,139,727",2011,[# 43][# 44]
24,25,20,Deadpool & Wolverine,"$1,338,073,645",2024,[# 45][# 46]
25,26,9,Star Wars: The Last Jedi,"$1,332,539,889",2017,[# 47][# 48]
26,27,12,Jurassic World: Fallen Kingdom,"$1,308,476,166",2018,[# 49][# 15]
27,28,5,Frozen,"F$1,290,000,000",2013,[# 50][# 51]
28,29,10,Beauty and the Beast,"$1,263,521,126",2017,[# 52][# 53]
29,30,15,Incredibles 2,"$1,242,805,359",2018,[# 54][# 15]
30,31,11,The Fate of the Furious,"F8$1,238,764,765",2017,[# 55][# 53]
31,32,5,Iron Man 3,"$1,214,811,252",2013,[# 56][# 57]
32,33,10,Minions,"$1,159,444,662",2015,[# 58][# 24]
33,34,12,Captain America: Civil War,"$1,153,337,496",2016,[# 59][# 60]
34,35,20,Aquaman,"$1,148,528,393",2018,[# 61][# 15]
35,36,2,The Lord of the Rings: The Return of the King,"$1,147,997,407",2003,[# 62][# 63]
36,37,37,Toy Story 5†,"$1,146,073,398",2026,[# 64]
37,38,24RK,Spider-Man: Far From Home,"$1,132,679,685",2019,[# 65][# 4]
38,39,23RK,Captain Marvel,"$1,128,274,794",2019,[# 66][# 67]
39,40,5RK,Transformers: Dark of the Moon,"$1,123,794,079",2011,[# 68][# 44]
40,41,7,Skyfall,"$1,108,594,137",2012,[# 69][# 70]
41,42,10,Transformers: Age of Extinction,"$1,104,054,072",2014,[# 71][# 72]
42,43JP,7,The Dark Knight Rises,"DKR$1,081,169,825",2012,[# 73][# 74]
43,44,31,Joker,"$1,074,458,282",2019,[# 75][# 35]
44,45,32,Star Wars: The Rise of Skywalker,"$1,074,144,248",2019,[# 76][# 35]
45,46,30,Toy Story 4,"$1,073,394,593",2019,[# 77][# 4]
46,47,4TS3,Toy Story 3,"$1,066,970,811",2010,[# 78][# 79]
47,48,3,Pirates of the Caribbean: Dead Man's Chest,"$1,066,179,747",2006,[# 80][# 81]
48,49,44,Moana 2,"$1,059,242,164",2024,[# 82][# 83]
49,50,20,Rogue One: A Star Wars Story,"$1,057,420,387",2016,[# 84][# 85]

In [ ]:
headers1=table1.find('tr')
cols1=[th.get_text(strip=True) for th in headers1 if th.get_text(strip=True)]
cols1

['Rank', 'Title', 'Worldwide gross(2025 $)', 'Year']

In [ ]:
trs=table1.find_all('tr')[1:]
row_data=[]
for t_row in trs:
  row=[t_data.get_text(strip=True) for t_data in t_row.find_all(['td','th'])]
  row_data.append(row)
row_data

[['1', 'Gone with the Wind', 'GW$4,561,000,000', '1939'],
 ['2', 'Avatar', 'A1$4,157,000,000', '2009'],
 ['3', 'Titanic', '$2,516,000,000T$3,864,000,000', '1997'],
 ['4', 'Star Wars', '$3,743,000,000', '1977'],
 ['5', 'Avengers: Endgame', 'AE$3,441,000,000', '2019'],
 ['6', 'The Sound of Music', '$3,138,000,000', '1965'],
 ['7', 'E.T. the Extra-Terrestrial', 'ET$3,065,000,000', '1982'],
 ['8', 'The Ten Commandments', '$2,898,000,000', '1956'],
 ['9', 'Doctor Zhivago', '$2,747,000,000', '1965'],
 ['10', 'Jaws', 'J$2,709,800,000', '1975']]

In [ ]:
df=pd.DataFrame(row_data,columns=cols1)
df

  Rank                       Title        Worldwide gross(2025 $)  Year
0    1          Gone with the Wind               GW$4,561,000,000  1939
1    2                      Avatar               A1$4,157,000,000  2009
2    3                     Titanic  $2,516,000,000T$3,864,000,000  1997
3    4                   Star Wars                 $3,743,000,000  1977
4    5           Avengers: Endgame               AE$3,441,000,000  2019
5    6          The Sound of Music                 $3,138,000,000  1965
6    7  E.T. the Extra-Terrestrial               ET$3,065,000,000  1982
7    8        The Ten Commandments                 $2,898,000,000  1956
8    9              Doctor Zhivago                 $2,747,000,000  1965
9   10                        Jaws                J$2,709,800,000  1975